"""Type hints for photo_dna_rs module."""

import pathlib
from typing import List, Tuple, Union

class Hash:
    @staticmethod
    def from_rgb_pixels(
        width: int, height: int, pixels: List[Tuple[int, int, int]]
    ) -> "Hash": ...
    @staticmethod
    def from_image_path(path: Union[str, pathlib.Path]) -> "Hash": ...
    @staticmethod
    def from_hex_str(hex_string: str) -> "Hash": ...
    @staticmethod
    def from_bytes(byte_data: bytes) -> "Hash": ...
    def as_bytes(self) -> bytes: ...
    def to_hex_str(self) -> str: ...
    def distance_euclidian(self, other: "Hash") -> float: ...
    def similarity_euclidian(self, other: "Hash") -> float: ...
    def distance_log2p(self, other: "Hash") -> float: ...
    def similarity_log2p(self, other: "Hash") -> float: ...

__all__ = ["Hash"]
